[project]
name = "checker"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "enochecker-core",
    "enochecker3",
]

[tool.uv]
override-dependencies = [
    "enochecker-core @ git+https://git.atklab.cloud/atklab/enochecker-core@v0.16.0",
]

[tool.uv.sources]
enochecker-core = { git = "https://git.atklab.cloud/atklab/enochecker-core", rev = "v0.16.0" }
enochecker3 = { git = "https://git.atklab.cloud/atklab/enochecker3", rev = "v0.16.0" }

[dependency-groups]
dev = [
    "enochecker-test>=0.14.4",
]
